"""add category to games

Revision ID: 135c8c032aba
Revises: 952f3fd8934c
Create Date: 2026-07-27 17:13:15.757683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135c8c032aba'
down_revision: Union[str, Sequence[str], None] = '952f3fd8934c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('rounds', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('rounds', sa.Column('imposter_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'imposter_id')
    op.drop_column('rounds', 'category')
    op.drop_column('games', 'category')
    # ### end Alembic commands ###
